group: bluezone

install:
  - sudo pip install ansible

script:
  - git clone git@github.ibm.com:immersive-env/packaging-tools.git
  - cd packaging-tools
  - ansible-playbook build-assets-deb.yml -i austin --extra-vars "project=ibm-aptmirror project_root=${TRAVIS_BUILD_DIR}"

deploy:
  provider: script
  script:
    - ansible-playbook package-assets.yml -i austin --extra-vars "project=ibm-aptmirror project_root=${TRAVIS_BUILD_DIR}"
  skip_cleanup: false
  on:
    branch: master
